# These options apply to how the script will operate.
script_options:
  # Setting TEST_MODE to False will use REAL funds, use at your own risk!
  TEST_MODE: True
  # Save trades to a log file.
  LOG_TRADES: True
  LOG_FILE: 'trades.txt'


# These options apply to the trading methods the script executes
trading_options:
  # select what to pair the coins to and pull all coins paied with PAIR_WITH
  PAIR_WITH: USDT

  # Total ammount per trade (e.g. in USDT)
  QUANTITY: 10

  # List of pairs to exlcude
  # by default we're excluding the most popular fiat pairs
  FIATS:
    - EUR-USDT
    - GBP-USDT
    - JPY-USDT
    - USD-USDT
    - DOWN
    - UP

  # Maximum number of trade 'slots' at any time (your USDT balance must be at least TRADE_SLOTS * QUANTITY)
  TRADE_SLOTS: 10

  # the amount of time in MINUTES to calculate the difference from the current price
  TIME_DIFFERENCE: 2

  # Numer of times to check for TP/SL during each TIME_DIFFERENCE Minimum 1
  RECHECK_INTERVAL: 10

  # the difference in % between the first and second checks for the price.
  CHANGE_IN_PRICE: 0.55

  # define in % when to sell a coin that's not making a profit
  STOP_LOSS: 4

  # define in % when to take profit on a profitable coin
  TAKE_PROFIT: 0.75

  # Use custom tickers.txt list for filtering pairs
  CUSTOM_LIST: True
   
  # Name of custom tickers list
  TICKERS_LIST: 'tickers.txt'
   
  # whether to use trailing stop loss or not; default is True
  USE_TRAILING_STOP_LOSS: True

  # Use custom signals list for checking TradingView's opinion of the current market state.
  CUSTOM_SIGNALS: False

  # Name of custom signals list
  SIGNALS_LIST: 'signalsample.txt'

  # Specify in minutes the frequency to check for trading signals from TradingView
  SIGNALS_FREQUENCY: 1

  # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
  # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
  TRAILING_STOP_LOSS: .02
  TRAILING_TAKE_PROFIT: .01
  
  # Trading fee in % per trade.
  TRADING_FEE: .08

  # show/hide additional data on bot screen. False = silent, True = spam (debug mode).
  VERBOSE_MODE: False
  
  SIGNALLING_MODULES:
    - pausebotmod
    #- custsignalmod_speed
    
  
